
# cargo-vet config file

[cargo-vet]
version = "0.8"

[[exemptions.ahash]]
version = "0.7.6"
criteria = "safe-to-run"

[[exemptions.aho-corasick]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.3.2"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.anstyle-parse]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.anstyle-query]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.anstyle-wincon]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.anyhow]]
version = "1.0.72"
criteria = "safe-to-run"

[[exemptions.approx]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.72"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.3.3"
criteria = "safe-to-run"

[[exemptions.bstr]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.bytecount]]
version = "0.6.3"
criteria = "safe-to-run"

[[exemptions.bytemuck]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.3.21"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.3.21"
criteria = "safe-to-run"

[[exemptions.clap_derive]]
version = "4.3.12"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.colorchoice]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.console]]
version = "0.15.7"
criteria = "safe-to-run"

[[exemptions.cucumber]]
version = "0.20.0"
criteria = "safe-to-run"

[[exemptions.cucumber-codegen]]
version = "0.20.0"
criteria = "safe-to-run"

[[exemptions.cucumber-expressions]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.derive_more]]
version = "0.99.17"
criteria = "safe-to-run"

[[exemptions.drain_filter_polyfill]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-run"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "1.9.0"
criteria = "safe-to-run"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-run"

[[exemptions.futures]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-channel]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-core]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-executor]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-io]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-lite]]
version = "1.13.0"
criteria = "safe-to-run"

[[exemptions.futures-macro]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-sink]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-task]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-util]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.2.10"
criteria = "safe-to-run"

[[exemptions.gherkin]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.globset]]
version = "0.4.11"
criteria = "safe-to-run"

[[exemptions.globwalk]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-run"

[[exemptions.heck]]
version = "0.4.1"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.3.2"
criteria = "safe-to-run"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-run"

[[exemptions.ignore]]
version = "0.4.20"
criteria = "safe-to-run"

[[exemptions.inflections]]
version = "1.1.1"
criteria = "safe-to-run"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-run"

[[exemptions.inventory]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.io-lifetimes]]
version = "1.0.11"
criteria = "safe-to-run"

[[exemptions.is-terminal]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.9"
criteria = "safe-to-run"

[[exemptions.lazy-regex]]
version = "3.0.0"
criteria = "safe-to-run"

[[exemptions.lazy-regex-proc_macros]]
version = "3.0.0"
criteria = "safe-to-run"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.147"
criteria = "safe-to-run"

[[exemptions.linked-hash-map]]
version = "0.5.6"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.3.8"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.19"
criteria = "safe-to-run"

[[exemptions.matrixmultiply]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.nalgebra]]
version = "0.32.3"
criteria = "safe-to-deploy"

[[exemptions.nalgebra-macros]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.nofmt]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-run"

[[exemptions.nom_locate]]
version = "4.1.0"
criteria = "safe-to-run"

[[exemptions.num-complex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.num-rational]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-run"

[[exemptions.parking]]
version = "2.1.0"
criteria = "safe-to-run"

[[exemptions.paste]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.peg]]
version = "0.6.3"
criteria = "safe-to-run"

[[exemptions.peg-macros]]
version = "0.6.3"
criteria = "safe-to-run"

[[exemptions.peg-runtime]]
version = "0.6.3"
criteria = "safe-to-run"

[[exemptions.pin-project]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.pin-project-internal]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.pin-project-lite]]
version = "0.2.10"
criteria = "safe-to-run"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.66"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.31"
criteria = "safe-to-deploy"

[[exemptions.rawpointer]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.37.23"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "0.38.4"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.15"
criteria = "safe-to-run"

[[exemptions.safe_arch]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.sealed]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.174"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.174"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.103"
criteria = "safe-to-run"

[[exemptions.simba]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.8"
criteria = "safe-to-run"

[[exemptions.smart-default]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.smawk]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.27"
criteria = "safe-to-run"

[[exemptions.synthez]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.synthez-codegen]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.synthez-core]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.terminal_size]]
version = "0.2.6"
criteria = "safe-to-run"

[[exemptions.textwrap]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.44"
criteria = "safe-to-run"

[[exemptions.thiserror-impl]]
version = "1.0.44"
criteria = "safe-to-run"

[[exemptions.thread_local]]
version = "1.1.7"
criteria = "safe-to-run"

[[exemptions.typed-builder]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.unicode-linebreak]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.utf8parse]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-run"

[[exemptions.waker-fn]]
version = "1.1.0"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.3.3"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-run"

[[exemptions.wide]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.45.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.48.1"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.0"
criteria = "safe-to-run"
